name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
        working-directory: automation-ui
      - name: Build
        run: GITHUB_PAGES=1 npm run build
        working-directory: automation-ui
        env:
          VITE_GH_PAGES_BASE: ${{ github.event.repository.name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: automation-ui/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
